version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # For development, you can mount the source code as a volume
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
